services:
  miniserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/miniserver/nginx.conf:/etc/nginx/nginx.conf

  nginx_proxy:
    image: nginx
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx_proxy/nginx.conf:/etc/nginx/nginx.conf
